name: publish-dummy-success-rfn-status.yml

on:
  pull_request_target:
    types: [auto_merge_enabled]

jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        HEAD_COMMIT: ${{ github.event.pull_request.head.sha }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/gogradle/test-merge-queue/statuses/$HEAD_COMMIT -d '{"state":"success","target_url":"https://builds.gradle.org/buildConfiguration/Gradle_Master_Check_Stage_ReadyforNightly_Trigger","description":"ReadyForNightly","context":"Ready for Nightly (Trigger) (Check)"}'
